Comvation:
  FusionForm:
    HCaptcha:
      # Override the test key and secret for production use
      siteKey: 10000000-ffff-ffff-ffff-000000000001
      siteSecret: 0x0000000000000000000000000000000000000000
      # size: compact # Smaller
      # size: invisible # Invisible, validates on submit
      # theme: dark
Neos:
  Neos:
    fusion:
      autoInclude:
        Comvation.FusionForm.HCaptcha: true
